```mermaid 
sequenceDiagram
   participant U as Utilisateur
   participant FC as FranceConnect
   participant FS as Fournisseur de Service
                       
   Note right of U : L'utilisateur clique <br/>sur le bouton <br/>"FranceConnect"
    
    FS->>FC: GET [issuer]/.well-known/openid-configuration
    FC-->>FS: HTTP 200
    Note left of FS : FS récupère les <br/>métadatas du FI

   U->>FC: GET / POST <FC_URL>/api/v2/authorize
   FC-->>U: Redirect 302 <FS_URL>/<URL_CALLBACK>

   U->>FS: GET <FS_URL>/<URL_CALLBACK>

   FS->>FC: POST <FC_URL>/api/v2/token
   FC-->>FS: HTTP Response 200

   FS->>FC: GET <FC_URL>/api/v2/userinfo
   FC-->>FS: HTTP Response 200

   FS-->>U: Redirect 302 <FS_URL>/page_authentifiée


   note right of U: Plus tard, <br /> l'utilisateur se <br/> déconnecte
                   
   U ->> FS: GET / POST ...
   FS-->>U: Redirect 302 <FC_URL>/api/v2/logout

   U->>FC: GET <FC_URL>/api/v2/logout
   FC-->>U: Redirect 302 <FC_URL>/<POST_LOGOUT_REDIRECT_URI>

   U-->FS: GET <FC_URL>/<POST_LOGOUT_REDIRECT_URI>

```